In [24]:
import torch
import numpy as np

# Find the the version of pytorch

In [2]:
torch.__version__

'2.1.0+cu118'

# Initializing Tensors

In [3]:
x=torch.tensor([1,2])
y=torch.tensor([3,4])

In [4]:
print(x)
print(y)

tensor([1, 2])
tensor([3, 4])


In [5]:
x1=torch.tensor([[1,2],[3,4]])
print(x1)

tensor([[1, 2],
        [3, 4]])


In [6]:
print(x.shape)
print(y.shape)
print(x1.shape)

torch.Size([2])
torch.Size([2])
torch.Size([2, 2])


In [7]:
print(type(x))
print(type(y))
print(type(x1))

<class 'torch.Tensor'>
<class 'torch.Tensor'>
<class 'torch.Tensor'>


In [8]:
print(x.dtype)

torch.int64


The datatype of all the elements in the tensor is the same. if the tensor contains data of different type, the entire tensor is coerced to the most generic type.

# Initializing tensor using Built in functions

# Tensor of zeros

In [9]:
zeros=torch.zeros((3,3))

In [10]:
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [11]:
zeros.dtype

torch.float32

# Tensor of ones

In [12]:
ones=torch.ones((3,3))

In [13]:
ones

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [14]:
print(ones.dtype
     )

torch.float32


# Creating tensor of random values between a specific range

torch.randint is user to generate random integer number between a specific range

In [15]:
T=torch.randint(low=0,high=10,size=(4,4))

In [16]:
T

tensor([[1, 3, 1, 1],
        [6, 6, 4, 2],
        [9, 3, 0, 2],
        [2, 7, 9, 3]])

In [17]:
T1=torch.randint(low=5,high=20,size=(3,3))

In [18]:
T1

tensor([[16, 10,  5],
        [ 6,  7,  8],
        [19,  7, 17]])

In [19]:
print(T1.dtype)

torch.int64


# Generating random numbers
### torch.randn is used to generate random numbers of mean =0 and std=1 (Normal distribution)

In [20]:
T2=torch.randn((3,3))

In [21]:
T2

tensor([[ 0.2379, -0.0865, -2.1358],
        [-0.5477,  0.8048,  0.3042],
        [ 0.4882, -0.2345,  1.2881]])

# Generating number numbers
### torch.rand is used to generate a sample from uniform normal distribution of range (0,1)


In [22]:
T3= torch.rand(3,4)

In [23]:
T3

tensor([[0.0448, 0.4760, 0.2592, 0.5926],
        [0.4294, 0.1544, 0.5747, 0.7675],
        [0.0851, 0.2915, 0.1072, 0.5465]])

# numpy array to torch tensor

In [25]:
x=np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [26]:
Y=torch.tensor(x)

In [28]:
print(x.dtype, Y.dtype)
print(type(x))
print(type(Y))

int32 torch.int32
<class 'numpy.ndarray'>
<class 'torch.Tensor'>


# operations on tensor

In [29]:
x=torch.tensor([[1,2,3,4,5],[6,7,8,9,10]])

In [30]:
print(x*20)

tensor([[ 20,  40,  60,  80, 100],
        [120, 140, 160, 180, 200]])


In [31]:
print(x.add(30))

tensor([[31, 32, 33, 34, 35],
        [36, 37, 38, 39, 40]])


# Element wise addition and element wise multiplication on tensors
### tensor1*tensor2 will perform element wise multiplication , corresponding element will be multiplied with corresponding element

In [36]:
x1=torch.rand(3,3)
y1=torch.rand(3,3)
print(x1)
print(y1)
print(x1*y1)
print(x1+y1)

tensor([[0.1719, 0.1221, 0.7725],
        [0.1035, 0.9690, 0.1669],
        [0.9629, 0.5059, 0.7678]])
tensor([[0.2401, 0.5897, 0.3494],
        [0.1819, 0.2941, 0.0674],
        [0.0624, 0.5453, 0.5035]])
tensor([[0.0413, 0.0720, 0.2699],
        [0.0188, 0.2850, 0.0112],
        [0.0601, 0.2759, 0.3866]])
tensor([[0.4119, 0.7118, 1.1219],
        [0.2854, 1.2631, 0.2342],
        [1.0253, 1.0512, 1.2713]])


# Matrix multiplication and matrix addition

In [40]:
x1=torch.rand(2,2)
y1=torch.rand(2,2)

multiplication=torch.matmul(x1,y1)
print("matrix multiplication",multiplication)
print("element wise multiplication", x1*y1)

matrix multiplication tensor([[1.3009, 0.3311],
        [0.6172, 0.1144]])
element wise multiplication tensor([[0.8376, 0.0547],
        [0.4597, 0.0601]])


In [44]:
"""
in the following example the rules for matrix multiplication is stasfied hence matrxi multiplication will be performed. but in
in the context of element wise multiplication y1 will be braodcasted to match the dimensions of x1 and hence multiplied element wise

"""

x1=torch.rand(2,2)
y1=torch.rand(2,1)

multiplication=torch.matmul(x1,y1)
elmentwise_multi=x1*y1
print("matrix multiplication",multiplication)
print("shape of matmul", multiplication.shape)
print("element wise multiplication", elmentwise_multi)
print("shape of elementwise_multi", elmentwise_multi.shape)

matrix multiplication tensor([[0.4260],
        [0.2497]])
shape of matmul torch.Size([2, 1])
element wise multiplication tensor([[0.2438, 0.0805],
        [0.4297, 0.0598]])
shape of elementwise_multi torch.Size([2, 2])


# Reshaping Tensor
### 1. view  ---> reshape a tensor to the specified shape without changing the data
### 2. Squeeze----> remone the dimension with size 1, reuduce the dimension of the tensor

In [49]:
tensor=torch.tensor([1,2,3,4,5,6])
print(tensor)
print(tensor.shape)
tensor=tensor.view((6,1))
print(tensor)
print(tensor.shape)

tensor=tensor.view((2,3))
print(tensor)
print(tensor.shape)

tensor([1, 2, 3, 4, 5, 6])
torch.Size([6])
tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])
torch.Size([6, 1])
tensor([[1, 2, 3],
        [4, 5, 6]])
torch.Size([2, 3])


In [52]:
#squeeze
x=torch.randn(10,1,10)
# print(x)
print(x.shape)

torch.Size([10, 1, 10])


In [53]:
x=torch.squeeze(x,1)

In [54]:
print(x.shape)

torch.Size([10, 10])


In [55]:
#squeeze
x=torch.randn(10,1,10)
# print(x)
print(x.shape)
x=x.squeeze(1)

torch.Size([10, 1, 10])


In [56]:
x.shape

torch.Size([10, 10])